[pytest]
# Modulul de setări Django
DJANGO_SETTINGS_MODULE = eventcalendar.settings

# Pattern-uri pentru fișierele de test
python_files = 
    test_*.py
    *_test.py

# Opțiuni suplimentare pentru pytest
addopts = --reuse-db

# Suprimă warning-ul Django 5.0
filterwarnings =
    ignore::django.utils.deprecation.RemovedInDjango50Warning
