# Generated by Django 4.2.16 on 2025-05-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Necunoscut', max_length=150, verbose_name='Prenume'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Necunoscut', max_length=150, verbose_name='Nume'),
        ),
    ]
