# Generated by Django 4.2.16 on 2025-05-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Pacient'), ('manager', 'Manager'), ('surgeon', 'Chirurg'), ('assistant', 'Asistenta')], default='patient', help_text='Select user role: Asistent, Manager sau Chirurg', max_length=10),
        ),
    ]
