# Generated by Django 4.2.16 on 2025-03-09 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='constrangeri_speciale',
            field=models.TextField(blank=True, default='Nicio constrângere', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='data_interventie',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='nume_pacient',
            field=models.CharField(default='Pacient Necunoscut', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='observatii',
            field=models.TextField(blank=True, default='Fără observații', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timp_estimare',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='event',
            name='tip_operatie',
            field=models.CharField(choices=[('curata', 'Curată'), ('murdara', 'Murdară'), ('laparoscopica', 'Laparoscopică')], default='curata', max_length=50),
        ),
    ]
