# Generated by Django 4.2.16 on 2025-03-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_remove_event_description_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('in_asteptare', 'În Așteptare'), ('aprobat', 'Aprobat'), ('respins', 'Respins'), ('finalizat', 'Finalizat')], default='in_asteptare', max_length=20),
        ),
    ]
