# Generated by Django 4.2.16 on 2025-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_event_sala_alocata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ora_inceput',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ora_sfarsit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
