# Generated by Django 4.2.16 on 2025-03-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_event_ora_inceput_event_ora_sfarsit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='durata',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
