# Generated by Django 5.1.3 on 2025-05-06 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_complet', models.CharField(max_length=200, verbose_name='Nume complet')),
                ('cnp', models.CharField(max_length=13, unique=True, verbose_name='CNP')),
                ('data_nasterii', models.DateField(verbose_name='Data nașterii')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='Sex')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('adresa', models.TextField(blank=True, null=True, verbose_name='Adresă')),
                ('istoric_medical', models.TextField(blank=True, null=True, verbose_name='Istoric medical')),
                ('chirurg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientii', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
