# Generated by Django 4.2.16 on 2025-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0011_pacient'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='status',
            field=models.CharField(choices=[('neprogramat', 'Neprogramat'), ('in_asteptare', 'În așteptare'), ('programat', 'Programat')], default='neprogramat', max_length=20),
        ),
    ]
