# Generated by Django 4.2.16 on 2025-05-14 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0012_pacient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asistenta_alocata',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'assistant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventii_asistate', to=settings.AUTH_USER_MODEL, verbose_name='Asistentă alocată'),
        ),
    ]
