# Generated by Django 4.2.16 on 2025-05-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0013_event_asistenta_alocata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status_live',
            field=models.CharField(choices=[('checked_in', 'Checked-In'), ('anes_start', 'Anestezie începută'), ('surgery_start', 'Operație începută'), ('pacu', 'PACU'), ('finalizat', 'Finalizat')], default='checked_in', max_length=20, verbose_name='Stadiu Intervenție (Live)'),
        ),
    ]
