# Generated by Django 4.2.16 on 2025-06-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0015_ultimaconfirmare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UltimaConfirmare',
        ),
    ]
