# Generated by Django 4.2.16 on 2025-06-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_delete_ultimaconfirmare'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatie',
            name='grad_complexitate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Scăzută'), (2, 'Medie'), (3, 'Înaltă')], default=1),
        ),
    ]
