# Generated by Django 4.2.16 on 2025-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0017_operatie_grad_complexitate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='justificare_prioritate',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prioritate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Scăzută'), (2, 'Normală'), (3, 'Înaltă')], default=2),
        ),
    ]
